name: starknet-demo
plugins:
  - name: starknet
  - name: cairo

default_ecosystem: starknet

dependencies:
  - name: OpenZeppelinCairo
    github: OpenZeppelin/cairo-contracts
    version: 0.6.0
    contracts_folder: src

cairo:
  dependencies:
    - OpenZeppelinCairo@0.6.0